### ISSUE TITLE
KeyError Issue

### ISSUE THREAD

**Issue by Bminnie90** [rhiever/tpot#188]
I am trying to run a simple csv. file as an example in tpot. The file does have some empty cells (is this the problem?). 

## What I typed and the response:
$ tpot /Users/bminniefield/Desktop/Bioinformatics/PPMI\ Study/EX_Family_History__PD_.csv -is , -o tpot_exported_pipeline.py -g 10 -v 2

TPOT settings:
CROSSOVER_RATE	=	0.05
GENERATIONS	=	10
INPUT_FILE	=	/Users/bminniefield/Desktop/Bioinformatics/PPMI Study/EX_Family_History__PD_.csv
INPUT_SEPARATOR	=	,
MUTATION_RATE	=	0.9
OUTPUT_FILE	=	tpot_exported_pipeline.py
POPULATION_SIZE	=	100
RANDOM_STATE	=	0
VERBOSITY	=	2

Traceback (most recent call last):
  File "/Users/bminniefield/anaconda/lib/python3.5/site-packages/pandas/indexes/base.py", line 1945, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 'class'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bminniefield/anaconda/bin/tpot", line 11, in <module>
    sys.exit(main())
  File "/Users/bminniefield/anaconda/lib/python3.5/site-packages/tpot/tpot.py", line 1848, in main
    stratify=input_data['class'].values,
  File "/Users/bminniefield/anaconda/lib/python3.5/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/Users/bminniefield/anaconda/lib/python3.5/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/Users/bminniefield/anaconda/lib/python3.5/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/Users/bminniefield/anaconda/lib/python3.5/site-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/Users/bminniefield/anaconda/lib/python3.5/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 'class'

##Additional Information: I am on command line, I am within the correct environment.

**Comment by teaearlgraycold** [comment]
What's the structure of your CSV?

**Comment by ankitshah009** [comment]
For the CSV - To use TPOT, we need to label columns as features and their corresponding class. 
F1,F2,.......,class <-- This could be the first row of the CSV and then have one's data to be able to use the generated pipeline from TPOT
