### ISSUE TITLE
Trying to run titanic example in pycharm

### ISSUE THREAD

**Issue by andrewcz** [rhiever/tpot#275]
/usr/bin/python3.4 "/home/andrewcz/PycharmProjects/tpot/tutorials/MAGIC Gamma Telescope/tpot_MAGIC_Gamma_Telescope_pipeline.py"
/home/andrewcz/PycharmProjects/tpot/tutorials/MAGIC Gamma Telescope/tpot_MAGIC_Gamma_Telescope_pipeline.py:8: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  tpot_data = pd.read_csv('PATH/TO/DATA/FILE', delimiter='COLUMN_SEPARATOR')
Traceback (most recent call last):
  File "/home/andrewcz/PycharmProjects/tpot/tutorials/MAGIC Gamma Telescope/tpot_MAGIC_Gamma_Telescope_pipeline.py", line 8, in <module>
    tpot_data = pd.read_csv('PATH/TO/DATA/FILE', delimiter='COLUMN_SEPARATOR')
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 315, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 645, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 805, in _make_engine
    self._engine = klass(self.f, **self.options)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 1590, in __init__
    compression=self.compression)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/common.py", line 424, in _get_handle
    f = open(path, mode, errors='replace')
FileNotFoundError: [Errno 2] No such file or directory: 'PATH/TO/DATA/FILE'

Process finished with exit code 1

Hi I am trying to run the python titanic example in pycharm and getting the above errors.
please help 
screenshot below.

![screenshot_2016-09-20_20-40-13](https://cloud.githubusercontent.com/assets/2296335/18667097/7ccacfd2-7f72-11e6-9be8-b0d1de5832a0.png)

**Comment by rhiever** [comment]
It looks like you're trying to run the generated code, which has a placeholder `'PATH/TO/DATA/FILE'` for the filename. You'll have to switch that placeholder out for the real filename, or not run that bit of generated code (which is meant only to be an example anyway).

**Comment by rhiever** [comment]
Were you able to solve this issue?
