### ISSUE TITLE
[Windows] - Anaconda 2 - InterruptableThread Problem

### ISSUE THREAD

**Issue by AntonBiryukovUofC** [rhiever/tpot#409]
## Context of the issue

Hello guys, a TPOT newbie here. I am trying to run the TPOTRegressor on some of my data, with nothing really fancy. My code dies at the fitting stage, by throwing a bunch of warnings (should they all appear in numbers first of all?), and then throwing an error.

I am on Windows 7 64bit, running Anaconda with python 2.7.

The dataset is 17 columns by ~2000 rows, nothing special in there, no NaNs, just some numbers...

Would sincerely appreciate any help on this.
## Process to reproduce the issue

1. I create TPOT instance:
my_tpot = TPOTRegressor(generations=100,verbosity=3)

2. I call TPOT `fit()` function with training data:

my_tpot.fit(X_train, y_train)

3. TPOT crashes:
Invalid pipeline encountered. Skipping its evaluation.<?, ?pipeline/s]
Traceback (most recent call last):                                    

  File "C:\Users\bia27988\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\bia27988\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:\tpot_mva.py", line 18, in <module>
    my_tpot.fit(X_train, y_train)

  File "C:\Users\bia27988\AppData\Local\Continuum\Anaconda2\lib\site-packages\tpot\base.py", line 413, in fit
    verbose=self.verbosity, max_time_mins=self.max_time_mins)

  File "C:\Users\bia27988\AppData\Local\Continuum\Anaconda2\lib\site-packages\tpot\gp_deap.py", line 138, in eaMuPlusLambda
    fitnesses = toolbox.evaluate(invalid_ind)

  File "C:\Users\bia27988\AppData\Local\Continuum\Anaconda2\lib\site-packages\tpot\base.py", line 753, in _evaluate_individuals
    resulting_score = _wrapped_cross_val_score(sklearn_pipeline)

  File "C:\Users\bia27988\AppData\Local\Continuum\Anaconda2\lib\site-packages\tpot\decorators.py", line 119, in limitedTime
    tmp_it.stop()

  File "C:\Users\bia27988\AppData\Local\Continuum\Anaconda2\lib\site-packages\tpot\decorators.py", line 99, in stop
    self._stop()

AttributeError: 'InterruptableThread' object has no attribute '_stop'

## Expected result

I thought it would just run and give me a pipeline 

## Possible fix
No idea yet.

**Comment by weixuanfu2016** [comment]
It is the same issue as #395. I think the current master branch already fixed this issue in python2.*. Please try the command below for reinstalling tpot. Let me know if the issue are fixed in your environment.

```
pip uninstall tpot
pip install git+https://github.com/rhiever/tpot.git
```

**Comment by AntonBiryukovUofC** [comment]
It definitely did ! Thanks a lot for help.

**Comment by rhiever** [comment]
We'll make sure to get those fixes out on pip as soon as we wrap a couple other patches up.
